fireball/api/urls.py
from django.conf.urls import patterns, include, url

from .api import BlobResource
from .api import UserResource


blob_resource = BlobResource()
user_resource = UserResource()


urlpatterns = patterns('',
    url(r'', include(blob_resource.urls)),
    url(r'', include(user_resource.urls)),
    url(r'^blobs/recent/(?P<page>\d*)/$', 'fireball.api.views.blobs_recent', name='blobs-recent'),
)

fireball/blobs/urls.py
from django.conf.urls import patterns, url
from . import views

urlpatterns = patterns('',
	url(r'^$', views.RecentView.as_view(), name='home'),
	url(r'^screenshot/(?P<blob_id>\d*)/$', views.SingleBlob, name='single'),
	url(r'^screenshot/full/(?P<blob_id>\d*)/$', views.FullSizeBlob, name='fullsize'),
	url(r'^(?P<username>[\w-]+)/$', views.UserView.as_view(), name='user'),
	
    url(r'^infinite/$', views.infinite, name='infinite'),
    url(r'^submit/$', views.new_blob, name='new-blob'),    
    
    #Delete
    url(r'^delete/(?P<blob_id>\d*)/$', views.delete_blob, name='delete-blob'),
    
    #Edit
    #url(r'^edit/(?P<blob_id>\d+)/$', views.edit_entry, name = 'edit-blob'),
    
    
)

fireball/core/urls.py
from django.conf.urls import patterns, url
from django.views.generic import TemplateView

urlpatterns = patterns('',
    url(r'^private/$', 'fireball.core.views.private', name='private'),
    url(r'^login/$', 'django.contrib.auth.views.login', {'template_name': 'core/login.html'}, name='login'),
    url(r'^register/$', 'fireball.core.views.register', name='register'),
    url(r'^logout/$', 'fireball.core.views.logout_user', name='logout'),

	#Static
	url(r'^about/$', TemplateView.as_view(template_name="static/about.html")),
	url(r'^about/api/$', TemplateView.as_view(template_name="static/api.html")),
	url(r'^about/terms/$', TemplateView.as_view(template_name="static/terms.html")),
	url(r'^about/privacy/$', TemplateView.as_view(template_name="static/privacy.html")),

)

fireball/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
	url(r'^admin/', include(admin.site.urls)),
    url(r'', include('fireball.core.urls', namespace='core')),
    url(r'', include('fireball.blobs.urls', namespace='blobs')),
    url(r'^api/', include('fireball.api.urls', namespace='api')),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.STATIC_ROOT,
    }),
)

fireball/blobs/models.py
from django.db import models
from django.core.files import File
from django.core.files.temp import NamedTemporaryFile
from django.contrib.auth.models import User
from django.core.files.uploadedfile import SimpleUploadedFile
from django.core.files.base import ContentFile
from django.utils.translation import ugettext_lazy as _
from django.conf import settings

import datetime
import os
import urllib2
from urlparse import urlparse
from cStringIO import StringIO
from PIL import Image

from taggit.managers import TaggableManager

def upload_collection_header(instance, filename):
	return 'images/collections/%s/%s' % (instance.user.id, filename)

class Collection(models.Model):
	title = models.CharField(max_length=250)
	slug = models.SlugField(max_length=250)
	description = models.TextField(max_length=500, blank=True, null=True)
	user = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='owned_collections')
	members = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, null=True, related_name='curator')
	pub_date = models.DateTimeField(auto_now_add=True)
	is_hidden = models.BooleanField(help_text=_("Should be checked if you dont want anyone to see."), default=False)
	tags = TaggableManager()
	
	def __unicode__(self):
		return "%s" % (self.name,)
		
	def get_absolute_url(self):
		return "/%s/%s/" % (self.owner, self.slug)    
	
	def save(self, *args, **kwargs):
		self.slug = slugify(self.title)
		super(Collection, self).save(*args, **kwargs)

	class Meta:
		ordering = ['-id']

def upload_original(instance, filename):
	return 'images/original/%s/%s' % (instance.user.id, filename)

def upload_thumb(instance, filename):
	return 'images/thumbnail/300/%s/%s' % (instance.user.id, filename)
			
class Blob(models.Model):
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	url = models.TextField(blank=True, null=True)
	description = models.TextField(blank=True, null=True)
	image = models.ImageField(upload_to=upload_original)
	thumbnail = models.ImageField(upload_to=upload_thumb)
	pub_date = models.DateTimeField(auto_now_add=True)
	collection = models.ForeignKey(Collection, blank=True, null=True)
	tags = TaggableManager()

	def __unicode__(self):
		return self.url

	def create_thumbnail(self, content_type=None):
		# original code for this method came from
		# http://snipt.net/danfreak/generate-thumbnails-in-django-with-pil/
		# If there is no image associated with this.
		# do not create thumbnail
		if not self.image:
			return

		# Set our max thumbnail size in a tuple (max width, max height)
		THUMBNAIL_SIZE = (400, 1000)

		DJANGO_TYPE = content_type if content_type else self.image.file.content_type

		if DJANGO_TYPE == 'image/jpeg':
			PIL_TYPE = 'jpeg'
			FILE_EXTENSION = 'jpg'
		elif DJANGO_TYPE == 'image/png':
			PIL_TYPE = 'png'
			FILE_EXTENSION = 'png'

		# Open original photo which we want to thumbnail using PIL's Image
		image = Image.open(StringIO(self.image.read()))

		# We use our PIL Image object to create the thumbnail, which already
		# has a thumbnail() convenience method that contrains proportions.
		# Additionally, we use Image.ANTIALIAS to make the image look better.
		# Without antialiasing the image pattern artifacts may result.
		image.thumbnail(THUMBNAIL_SIZE, Image.ANTIALIAS)

		# Save the thumbnail
		temp_handle = StringIO()
		image.save(temp_handle, PIL_TYPE)
		temp_handle.seek(0)
		
		# Save image to a SimpleUploadedFile which can be saved into

		# ImageField
		suf = SimpleUploadedFile(os.path.split(self.image.name)[-1],
				temp_handle.read(), content_type=DJANGO_TYPE)
		# Save SimpleUploadedFile into image field
		self.thumbnail.save('%s_thumbnail.%s'%(os.path.splitext(suf.name)[0],FILE_EXTENSION), suf, save=False)

	def save(self):
		if not self.id:
			if self.url and not self.image:
				name = urlparse(self.url).path.split('/')[-1]
				extension = name.split('.')[-1]
				if extension == "jpg":
					content_type = "image/jpeg"
				elif extension == "png":
					content_type = "image/png"
				else:
					content_type = "text/plain"
					#TODO: Do something if this file isn't supported???
	
				#wrap your file content
				content = SimpleUploadedFile(name, urllib2.urlopen(self.url).read(), content_type=content_type)
				self.image.save(name, content, save=False)
	
				# create a thumbnail
				self.create_thumbnail(content_type)
			else:
				self.create_thumbnail()
		super(Blob, self).save() 


	class Meta:
		ordering = ['-id']

class Attachment(models.Model):
	blob = models.ForeignKey(Blob)
	user = models.ForeignKey(settings.AUTH_USER_MODEL)
	description = models.TextField(blank=True, null=True)
	pub_date = models.DateTimeField(auto_now_add=True)
	
	def get_absolute_url(self):
		return "/attachments/%s/" % (self.id)
		

class BlobView(models.Model):
    blob = models.ForeignKey(Blob, related_name='blobviews')
    ip = models.CharField(max_length=40)
    session = models.CharField(max_length=40)
    created = models.DateTimeField(default=datetime.datetime.now())
    

fireball/core/models.py
import datetime

from django.contrib.auth.models import UserManager, AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _

GENDER_CHOICES = (
	('F', _('Female')),
	('M', _('Male')),
	('P', _('Pirate')),
	('N', _('Ninja')),
	('R', _('Robot')),
)

PROFILE_OPTIONS = (
	('1', _('Scale To Fit')),
	('2', _('Repeated')),
	('3', _('Do Not Scale')),
)

def upload_profile(instance, filename):
	return 'images/profile/%s/%s' % (instance.id, filename)

class Profile(AbstractUser):
	gender			  = models.CharField(max_length=1, choices=GENDER_CHOICES, blank=True)
	location 		  = models.CharField(max_length=255, blank=True)
	url				  = models.URLField(max_length=500, blank=True)
	about			  = models.TextField(max_length=500, blank=True)
	
	#Porfile header
	image 			  = models.ImageField(upload_to=upload_profile, blank=True)
	image_position	  = models.CharField(max_length=1, choices=PROFILE_OPTIONS, blank=True)
	
	#Settings
	hide_mobile       = models.BooleanField(default=False)
	last_seen_on      = models.DateTimeField(default=datetime.datetime.now)
	preferences       = models.TextField(default="{}")
	view_settings     = models.TextField(default="{}")
	send_emails       = models.BooleanField(default=False)
	is_beta			  = models.BooleanField(default=False)
	

fireball/blobs/forms.py
from django import forms

from .models import Blob


class BlobForm(forms.ModelForm):
	url = forms.CharField(label='URL', required=False)
	image = forms.ImageField(label='or Upload', required=False)


	def __init__(self, *args, **kwargs):
		super(forms.ModelForm, self).__init__(*args, **kwargs)
		self.fields.keyOrder = (
			'url',
			'image',
			'description',
			'collection',
		)


	def check_if_image(self, data):
		# Test file type
		image_file_types = ['png', 'gif', 'jpeg', 'jpg']
		file_type = data.split('.')[-1]
		if file_type.lower() not in image_file_types:
			raise forms.ValidationError("Requested URL is not an image file. "
										"Only images are currently supported.")

	def clean(self):
		cleaned_data = super(BlobForm, self).clean()

		url = cleaned_data.get('url')
		image = cleaned_data.get('image')

		if url:
			self.check_if_image(url)
			try:
				Blob.objects.get(url=url)
				raise forms.ValidationError("URL has already been saved.")
			except Blob.DoesNotExist:
				try:
					Blob.objects.get(url=url)
					raise forms.ValidationError("URL has already been saved.")
				except Blob.DoesNotExist:
					pass
		elif image:
			pass
		else:
			raise forms.ValidationError("Need either a URL or Upload.")

		return cleaned_data

	class Meta:
		model = Blob
		exclude = ['user', 'thumbnail']

fireball/api/views.py
from django.utils import simplejson
from django.http import HttpResponse , HttpResponseRedirect
from fireball.blobs.models import Blob
from django.core.files import File
from django.core.files.images import ImageFile
from django.template.response import TemplateResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import redirect_to_login 
from django.contrib.auth.models import User
import urllib2
import hashlib

def blobs_user_recent(request, user_id=1, page=1):
    start_blob = abs(int(page) - 1) * 25
    end_blob = int(page) * 25

    blobs = Blob.objects.order_by('-id').filter(author=user_id)
    recent_blobs = []
    for blob in blobs:
        recent_blobs.append({
            'id': blob.id,
            'thumbnail': blob.image.url.rstrip('.jpg')+".200x1000.jpg",
            'original': blob.image.url,
            'description': blob.description,
            'username' : blob.user.username,
        })

    return HttpResponse(simplejson.dumps(recent_blobs), mimetype="application/json")

def blobs_recent(request, page=1):
    start_blob = abs(int(page) - 1) * 25
    end_blob = int(page) * 25

    blobs = Blob.objects.order_by('-id')[start_blob:end_blob]
        
    recent_blobs = []
    for blob in blobs:
        recent_blobs.append({
            'id': blob.id,
            'thumbnail': blob.thumbnail.url,
            'image': blob.image.url,
            'description': blob.description,
            'url': blob.url,
            'username' : blob.user.username,
            'user_id' : blob.user.id,
            'email_hash': hashlib.md5(blob.user.email).hexdigest(),
        })

    return HttpResponse(simplejson.dumps(recent_blobs), mimetype="application/json")

fireball/blobs/views.py
import datetime

from django.template.response import TemplateResponse
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from django.views.generic.list import ListView
from django.shortcuts import render_to_response, render, get_object_or_404, redirect
from django.template import RequestContext

from fireball.core.models import Profile
from taggit.models import Tag
from .forms import BlobForm
from .models import Blob, BlobView

class RecentView(ListView):
	paginate_by = 50
	template_name = 'blobs/blob_list.html'

	def get_queryset(self):
		return Blob.objects.order_by('-pub_date')

	def get_context_data(self, **kwargs):
		context = super(RecentView, self).get_context_data(**kwargs)
		context.update({'headers': False,})
		return context

class UserView(ListView):
	paginate_by = 50
	template_name = 'blobs/blob_list.html'

	def get_queryset(self):
		self.u = get_object_or_404(Profile, username=self.kwargs.pop('username'))
		self.latest = Blob.objects.filter(user__username=self.u).latest('pub_date')
		return Blob.objects.filter(user__username=self.u).order_by('-pub_date')

	def get_context_data(self, **kwargs):
		context = super(UserView, self).get_context_data(**kwargs)
		context.update({'headers': True, 'profile': True, 'user_obj': self.u, 'latest': self.latest,})
		return context

def SingleBlob(request, blob_id):
	blob = get_object_or_404(Blob, pk=blob_id)
	
	if not BlobView.objects.filter(blob=blob, session=request.session.session_key):
	        view = BlobView(blob=blob, ip=request.META['REMOTE_ADDR'], created=datetime.datetime.now(), session=request.session.session_key)
	        view.save()
	
	view_count = BlobView.objects.filter(blob=blob).count()
	tags = blob.tags.all()
	variables = RequestContext(request, {'object': blob, 'tags': tags, 'view_count': view_count,})
	return render_to_response('blobs/single_blob.html', variables)

def FullSizeBlob(request, blob_id):
	blob = get_object_or_404(Blob, pk=blob_id)
	variables = RequestContext(request, {'object': blob})
	return render_to_response('blobs/fullsize_blob.html', variables)
	
def infinite(request):
    return TemplateResponse(request, 'blobs/infinite.html', None)


def new_blob(request):
    if request.method == 'POST':
        form = BlobForm(request.POST, request.FILES)
        if form.is_valid():
            blob = form.save(commit=False)
            blob.user = request.user
            blob.save()
            messages.success(request, 'New blob successfully added.')
            return HttpResponseRedirect(reverse('blobs:home'))
        else:
            messages.error(request, 'Blob did not pass validation!')
    else:
        form = BlobForm()
    context = {
        'form': form,
    }
    return TemplateResponse(request, 'blobs/new_blob.html', context)


def delete_blob(request, blob_id):
    try:
        blob = Blob.objects.get(id=blob_id)
        if blob.user == request.user:
            blob.delete()
            messages.success(request, 'Blob successfully deleted.')
        else:
            messages.error(request, 'You are not the user and can not '
                                    'delete this blob.')
    except Blob.DoesNotExist:
        messages.error(request, 'Blob with the given id does not exist.')
        

    return HttpResponseRedirect(reverse('blobs:home'))

fireball/core/views.py
from django.template.response import TemplateResponse
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.conf import settings


def private(request):
    return TemplateResponse(request, 'core/private.html', None)


def register(request):
    if not settings.ALLOW_NEW_REGISTRATIONS:
        messages.error(request, "The admin of this service is not "
                                "allowing new registrations.")
        return HttpResponseRedirect(reverse('blobs:home'))
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Thank you for registering, you can now '
                                      'login.')
            return HttpResponseRedirect(reverse('core:login'))
    else:
        form = UserCreationForm()

    return TemplateResponse(request, 'core/register.html', {'form': form})


@login_required
def logout_user(request):
    logout(request)
    messages.success(request, 'You have successfully logged out.')
    return HttpResponseRedirect(reverse('blobs:home'))

fireball/templates/blobs/blob_list.html
{% extends 'core/base.html' %}{% load humanize %}{% load compress %}{% load core %}

{% block title %}
{% if profile %}{{ user_obj }}
{% else %}Recent blobs{% endif %}
{% endblock %}

{% block yield %}

{% if profile %}
{% if user_obj.image %}
<div class="profile-header" id="{{ user_obj }}" style="background-image: url('{{ user_obj.image.url }}');">
{% else %}
<div class="profile-header" id="{{ user_obj }}" style="background-image: url('{{ latest.image.url }}');">
{% endif %}
	<div class="user-meta">
		<img id="avatar" width="32" height="32" src="https://secure.gravatar.com/avatar/{{ user_obj|email_hash }}?s=64" />
		<h2>{{ user_obj }}</h2>
		
		<ul class="nav nav-tabs">
			<li class="active"><a href="#">Images</a></li>
			<li><a href="#">Collections</a></li>
			<li><a href="#">Tags</a></li>
			<li><a href="#">Likes</a></li>
		</ul>
		
	</div>
</div>
{% endif %}

<ul id="blobs" class="unstyled">
	{% for blob in object_list %}
	<li class="blob" id="blob-{{ blob.id }}">
	    
	    <div class="photo">
	    	<a href="{% url 'blobs:single' blob.id %}"><img src="{{ blob.thumbnail.url }}" width="200" ></a>
	    </div>
	    
	    <div class="meta">
	    	<span class="description">{{ blob.description }}</span>
	    	<img class="pull-left" id="avatar" width="32" height="32" src="https://secure.gravatar.com/avatar/{{ blob.user|email_hash }}?s=32" />
	    	<span class="date">{{ blob.pub_date|naturaltime }}</span>
	    	<span class="username">by <a href="{% url 'blobs:user' blob.user %}">{{ blob.user }}</a></span>
	    </div>
	</li>
  	{% endfor %}	
</ul>
{% endblock %}

fireball/templates/blobs/fullsize_blob.html
<!DOCTYPE html>
<html> {% load compress %}{% load core %}{% load humanize %}
    <head>
        <title>{{ object.description }}</title>

        {% compress css %}
            <link rel="stylesheet" href="/static/css/bootstrap.css">
            <link rel="stylesheet" href="/static/css/fullsize.css">
        {% endcompress %}

    </head>
    <body>    
        	    		
		<div id="fullsize">
		
        		<div class="meta">
        			<span class="username"><a href="{% url 'blobs:user' object.user %}">{{ object.user }}</a></span>
        			<span class="date">{{ object.pub_date|naturaltime }}</span>
        			
        			<span class="description">{{ object.description }}</span>
        		</div>
        		
        		<div class="blob">
        			<img src="{{ object.image.url }}" alt="{{ object.description }}" />		
        		</div>

		</div>
    </body>
</html>

fireball/templates/blobs/infinite.html
{% extends 'core/base.html' %}

{% block title %}Recent blobs{% endblock %}

{% block yield %}
    <div id="blobs"></div>
    
    <div id="loader" class="container">
        <div class="row">
            <div class="span2 offset5">
                <img src="/static/img/loading.gif" alt="Loader">
            </div>
        </div>
    </div>
{% endblock %}

fireball/templates/blobs/new_blob.html
{% extends 'core/base.html' %}

{% load bootstrap_field %}


{% block title %}New Blob{% endblock %}

{% block yield %}
    <div class="container">
        <div class="row">
            <div class="span6 offset3" id="form">
                <h1>New Blob</h1>
                {{ form.non_field_errors }}
                <form enctype="multipart/form-data" action="{% url 'blobs:new-blob' %}" method="post" class="form-horizontal">
                    {% csrf_token %}
                    {% for field in form %}
                        {% bootstrap_field field %}
                    {% endfor %}
                    <div class="form-actions">
                        <button type="submit" class="btn btn-primary">Post</button>
                        <a href="{% url 'blobs:home' %}" class="btn">Cancel</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

fireball/templates/blobs/single_blob.html
{% extends 'core/base.html' %}{% load humanize %}{% load compress %}{% load core %}

{% block title %}{{ object.description }}{% endblock %}

{% block yield %}
<div class="container">
	<div class="row">
	<div class="span6 single-blob">
		
		<div class="meta">
			<img class="pull-left" id="avatar" width="64" height="64" src="https://secure.gravatar.com/avatar/{{ object.user|email_hash }}?s=64" />
			<span class="username"><a href="{% url 'blobs:user' object.user %}">{{ object.user }}</a></span>
			<span class="date">{{ object.pub_date|naturaltime }}</span>
			<div class="clearfix"></div>
		</div>
		
		<div class="blob">
			<img src="{{ object.thumbnail.url }}" alt="{{ object.description }}" />		
		</div>
		
		
		<div class="comments">
		<h3>Responses</h3>
		</div>
		
	</div><!-- span8 -->
	
	<div class="span4">
		<ul class="unstyled blob-details">
			<li><i class="icon-heart"></i> Like</li>
			<li><i class="icon-share"></i> Share</li>
			<li><i class="icon-eye-open"></i> {{ view_count }} Views</li>
			<li><a href="{% url 'blobs:fullsize' object.id %}"><i class="icon-picture"></i> Fullsize</a></li>
			<li><h4>Description</h4>
				<span class="description">{{ object.description }}</span>
			</li>
			<li><h4>Tags</h4>
				<ul class="unstyled tags">
				
				{% for tag in tags %}
				<li class="tag"><a class="{{ tag|slugify }}" href="/tags/{{ tag|slugify }}/">{{ tag }}</a></li>
				{% empty %}
				<li class="tag">No tags yet.</li>
				{% endfor %}
				
				</ul>
			</li>
		</ul>
	</div>
	
	</div><!-- row -->
</div>
{% endblock %}